
types = ["survival/crafting", "action", "simulation", "turn-based rpg", "open-world rpg", "metroidvania", "rogue-like", "first-person shooter", "third-person shooter", "comedy", "puzzle", "sandbox", "social deduction", "horror", "crpg"]

video_games = [['social deduction', '2D', 'Among Us', 'Innersloth', 'Very Positive'],
               ['action', '3D', "Assassin's Creed", 'Ubisoft', 'Very Positive'],
               ['survival/crafting', '3D', 'Astroneer', 'System Era Softworks', 'Very Positive'],
               ['crpg', '3D', "Baldur's Gate 3", 'Lirian Studios', 'Overwhelmingly Positive'],
               ['action', '3D', 'Bastion', 'Supergiant Games', 'Overwhelmingly Positive'],
               ['simulation', '3D', 'Besiege', 'Spiderling Studios', 'Overwhelmingly Positive'],
               ['first-person shooter', '3D', 'Borderlands', 'Gearbox Software/2K', 'Overwhelmingly Positive'],
               ['metroidvania', '2D', 'Cave Story', 'Nicalis, Inc.', 'Very Positive'],
               ['turn-based rpg', '2D', 'Child of Light', 'Ubisoft', 'Very Positive'],
               ['open-world rpg', '3D', 'Elden Ring', 'FromSoftware Inc.', 'Very Positive'],
               ['rogue-like', '2D', 'Dead Cells', 'Motion Twin', 'Overwhelmingly Positive'],
               ['open-world rpg', '3D', 'Dragon Age Inquisition', 'EA/Bioware', 'Mostly Positive'],
               ['rogue-like', '2D', 'Dungeon Souls', 'Lamina Studios', 'Mostly Positive'],
               ['open-world rpg', '3D', 'Skyrim', 'Bethesda', 'Very Positive'],
               ['open-world rpg', '3D', 'Fallout 4', 'Bethesda', 'Very Positive'],
               ['first-person shooter', '3D', 'Far Cry', 'Ubisoft', 'Very Positive'],
               ['horror', '3D', "Five Nights at Freddy's", 'Scott Cawthon', 'Very Positive'],
               ['sandbox', '3D', "Garry's Mod", 'Valve', 'Overwhelmingly Positive'],
               ['metroidvania', '2D', 'Ghost 1.0', 'Unepic Games', 'Very Positive'],
               ['first-person shooter', '3D', 'Half-Life 2', 'Valve', 'Overwhelmingly Positive'],
               ['first-person shooter', '3D', 'Left 4 Dead 2', 'Valve', 'Overwhelmingly Positive'],
               ['comedy', '3D', 'Magicka', 'Paradox Interactive', 'Very Positive'],
               ['comedy', '3D', 'Trover Saves the Universe', 'Squanch Games, Inc.', 'Very Positive'],
               ['third-person shooter', '3D', 'Mass Effect', 'EA/Bioware', 'Very Positive'],
               ['metroidvania', '2D', 'Ori and the Blind Forest', 'Moon Studios GmbH', 'Overwhelmingly Positive'],
               ['puzzle', '3D', 'Portal 2', 'Valve', 'Overwhelmingly Positive'],
               ['action', '3D', 'Prince of Persia', 'Mostly Positive'],
               ['action', '3D', 'Prototype', 'Mostly Positive'],
               ['survival/crafting', '3D', 'Raft', 'Axolot Games/Redbeet Interactive', 'Very Positive'],
               ['action', '3D', 'Remember Me', 'Capcom', 'Very Positive'],
               ['metroidvania', '2D', 'Shantae', 'WayForward', 'Very Positive'],
               ['sandbox', '3D', 'Spore', 'EA/Maxis', 'Very Positive'],
               ['sandbox', '2D', 'Starbound', 'Chucklefish', 'Very Positive'],
               ['simulation', '2D', 'Stardew Valley', 'ConcernedApe', 'Overwhelmingly Positive'],
               ['open-world rpg', '3D', 'Starfield', 'Bethesda', 'Mixed'],
               ['horror', '3D', 'Subnautica', 'Unknown Worlds Entertainment', 'Overwhelmingly Positive'],
               ['metroidvania', '2D', 'Sundered', 'Thunder Lotus Games', 'Very Positive'],
               ['survival/crafting', '2D', 'Terraria', 'Re-Logic', 'Overwhelmingly Positive'],
               ['third-person shooter', '3D', 'Tomb Raider', 'Crystal Dynamics, Eidos,...', 'Overwhelmingly Positive'],
               ['social deduction', '2D', 'Town of Salem', 'BlankMediaGames LLC', 'Mostly Positive'],
               ['social deduction', '3D', 'West Hunt', 'Wandering Wizard/NewGen', 'Very Positive'],
               ['turn-based rpg', '2D', 'Darkest Dungeon', 'Red Hook Studios', 'Very Positive'],
               ['puzzle', '3D', 'It Takes Two', 'EA/Hazelight', 'Very Positive'],
               ['puzzle', '2D', 'Animal Well', 'Bigmode/Billy Basso', 'Overwhelmingly Positive'],
               ['crpg', '2D', 'Caves of Qud', 'Kitfox Games/Freehold Games', 'Overwhelmingly Positive'],
               ['crpg', '3D', 'Pathfinder: Wrath of the Righteous', 'Owlcat Games', 'Very Positive'],
               ['horror', '3D', 'Dying Light', 'Techland', 'Overwhelmingly Positive'],
               ['horror', '3D', 'Lethal Company', 'Zeekerss', 'Overwhelmingly Positive'],
               ['simulation', '3D', 'PowerWash Simulator', 'Square Enix/FuturLab', 'Overwhelmingly Positive'],
               ['simulation', '3D', 'Microsoft Flight Simulator', 'Asobo Studio', 'Mostly Positive']
]
video_games.sort()
types.sort()
#print(types)