
types = ["Survival/Crafting", "Action", "Simulation", "Turn-Based RPG", "Open-World RPG", "Metroidvania", "Rogue-like", "First-Person Shooter", "Third-Person Shooter", "Comedy", "Puzzle", "Sandbox", "Social Deduction", "Horror", "CRPG"]

video_games = [['Social Deduction', '2D', 'Among Us', 'Innersloth', 'Very Positive'],
               ['Action', '3D', "Assassin's Creed", 'Ubisoft', 'Very Positive'],
               ['Survival/Crafting', '3D', 'Astroneer', 'System Era Softworks', 'Very Positive'],
               ['CRPG', '3D', "Baldur's Gate 3", 'Lirian Studios', 'Overwhelmingly Positive'],
               ['Action', '3D', 'Bastion', 'Supergiant Games', 'Overwhelmingly Positive'],
               ['Simulation', '3D', 'Besiege', 'Spiderling Studios', 'Overwhelmingly Positive'],
               ['First-Person Shooter', '3D', 'Borderlands', 'Gearbox Software/2K', 'Overwhelmingly Positive'],
               ['Metroidvania', '2D', 'Cave Story', 'Nicalis, Inc.', 'Very Positive'],
               ['Turn-Based RPG', '2D', 'Child of Light', 'Ubisoft', 'Very Positive'],
               ['Open-World RPG', '3D', 'Elden Ring', 'FromSoftware Inc.', 'Very Positive'],
               ['Rogue-like', '2D', 'Dead Cells', 'Motion Twin', 'Overwhelmingly Positive'],
               ['Open-World RPG', '3D', 'Dragon Age Inquisition', 'EA/Bioware', 'Mostly Positive'],
               ['Rogue-like', '2D', 'Dungeon Souls', 'Lamina Studios', 'Mostly Positive'],
               ['Open-World RPG', '3D', 'Skyrim', 'Bethesda', 'Very Positive'],
               ['Open-World RPG', '3D', 'Fallout 4', 'Bethesda', 'Very Positive'],
               ['First-Person Shooter', '3D', 'Far Cry', 'Ubisoft', 'Very Positive'],
               ['Horror', '3D', "Five Nights at Freddy's", 'Scott Cawthon', 'Very Positive'],
               ['Sandbox', '3D', "Garry's Mod", 'Valve', 'Overwhelmingly Positive'],
               ['Metroidvania', '2D', 'Ghost 1.0', 'Unepic Games', 'Very Positive'],
               ['First-Person Shooter', '3D', 'Half-Life 2', 'Valve', 'Overwhelmingly Positive'],
               ['First-Person Shooter', '3D', 'Left 4 Dead 2', 'Valve', 'Overwhelmingly Positive'],
               ['Comedy', '3D', 'Magicka', 'Paradox Interactive', 'Very Positive'],
               ['Comedy', '3D', 'Trover Saves the Universe', 'Squanch Games, Inc.', 'Very Positive'],
               ['Third-Person Shooter', '3D', 'Mass Effect', 'EA/Bioware', 'Very Positive'],
               ['Metroidvania', '2D', 'Ori and the Blind Forest', 'Moon Studios GmbH', 'Overwhelmingly Positive'],
               ['Puzzle', '3D', 'Portal 2', 'Valve', 'Overwhelmingly Positive'],
               ['Action', '3D', 'Prince of Persia', 'Mostly Positive'],
               ['Action', '3D', 'Prototype', 'Mostly Positive'],
               ['Survival/Crafting', '3D', 'Raft', 'Axolot Games/Redbeet Interactive', 'Very Positive'],
               ['Action', '3D', 'Remember Me', 'Capcom', 'Very Positive'],
               ['Metroidvania', '2D', 'Shantae', 'WayForward', 'Very Positive'],
               ['Sandbox', '3D', 'Spore', 'EA/Maxis', 'Very Positive'],
               ['Sandbox', '2D', 'Starbound', 'Chucklefish', 'Very Positive'],
               ['Simulation', '2D', 'Stardew Valley', 'ConcernedApe', 'Overwhelmingly Positive'],
               ['Open-World RPG', '3D', 'Starfield', 'Bethesda', 'Mixed'],
               ['Horror', '3D', 'Subnautica', 'Unknown Worlds Entertainment', 'Overwhelmingly Positive'],
               ['Metroidvania', '2D', 'Sundered', 'Thunder Lotus Games', 'Very Positive'],
               ['Survival/Crafting', '2D', 'Terraria', 'Re-Logic', 'Overwhelmingly Positive'],
               ['Third-Person Shooter', '3D', 'Tomb Raider', 'Crystal Dynamics, Eidos,...', 'Overwhelmingly Positive'],
               ['Social Deduction', '2D', 'Town of Salem', 'BlankMediaGames LLC', 'Mostly Positive'],
               ['Social Deduction', '3D', 'West Hunt', 'Wandering Wizard/NewGen', 'Very Positive'],
               ['Turn-Based RPG', '2D', 'Darkest Dungeon', 'Red Hook Studios', 'Very Positive'],
               ['Puzzle', '3D', 'It Takes Two', 'EA/Hazelight', 'Very Positive'],
               ['Puzzle', '2D', 'Animal Well', 'Bigmode/Billy Basso', 'Overwhelmingly Positive'],
               ['CRPG', '2D', 'Caves of Qud', 'Kitfox Games/Freehold Games', 'Overwhelmingly Positive'],
               ['CRPG', '3D', 'Pathfinder: Wrath of the Righteous', 'Owlcat Games', 'Very Positive'],
               ['Horror', '3D', 'Dying Light', 'Techland', 'Overwhelmingly Positive'],
               ['Horror', '3D', 'Lethal Company', 'Zeekerss', 'Overwhelmingly Positive'],
               ['Simulation', '3D', 'PowerWash Simulator', 'Square Enix/FuturLab', 'Overwhelmingly Positive'],
               ['Simulation', '3D', 'Microsoft Flight Simulator', 'Asobo Studio', 'Mostly Positive'],
               
]